org: serverless-cnode-nuxtjs
app: serverless-cnode-nuxtjs
stage: dev
component: layer
name: serverless-cnode-nuxtjs-layer

inputs:
  region: ${env:REGION}
  name: ${name}
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs10.15
    - Nodejs12.16
